data_processing:
  label_col: category
  test_data_size: 0.1
  text_col: text
  train_data_size: 0.6
  val_data_size: 0.3
labels:
- business
- entertainment
- politics
- sport
- tech
model_params:
  epochs: 5
  model_name: bert-base-uncased
  train_batch_size: 4
  val_batch_size: 4
num_labels: 5
