data_processing:
  label_col: category
  test_data_size: 0.2
  text_col: text
  train_data_size: 0.5
  val_data_size: 0.3
labels:
- tech
- business
- sport
- entertainment
- politics
model_params:
  epochs: 8
  model_name: bert-base-cased
  train_batch_size: 4
  val_batch_size: 4
num_labels: 5
