data_processing:
  text_col: text
  label_col: category
  train_data_size: 0.7
  val_data_size: 0.1
  test_data_size: 0.2


num_labels: 5
labels : []

model_params:
  model_name: bert-base-uncased
  epochs : 5
  train_batch_size: 4
  val_batch_size: 4



