artifacts_root: artifacts

data_ingestion:
  raw_data_dir: artifacts/raw_data
  web_data_dir: web_files

data_processing:
  raw_data_dir: artifacts/raw_data
  processed_data_dir: artifacts/processed_data
  split_data_dir: artifacts/split_data
  save_tokenizer: artifacts/models/

train_model:
  train_data_path: artifacts/split_data/
  val_data_path : artifacts/split_data/
  saved_model_dir: artifacts/models

evaluate_model:
  saved_model_dir: artifacts/models
  test_data_path: artifacts/split_data/


